


export enum IdentificationDocumentStatus {
    FAKE_DOCUMENT = "FAKE_DOCUMENT",
    NOT_VERIFIED = "NOT_VERIFIED",
    VERIFIED = "VERIFIED",
    EXPIRED= "EXPIRED",
    BLACK_LISTED_COUNTRY = "BLACK_LISTED_COUNTRY",
    BLACK_LISTED_PERSON = "BLACK_LISTED_PERSON",
    KYC_REJECTED = "KYC_REJECTED",
    ADVERSE_MEDIA_PERSON = "ADVERSE_MEDIA_PERSON",
}
