import { EntityBase } from "../../Entities/Base/EntityBase";

export interface PomeloPresentment extends EntityBase {
    id: string,
    publicId: string | null,
    transactionId: string | null,
    transactionDateTime: string | null,
    transactionType: string | null,
    productType: string | null,
    provider: string | null,
    userId: string | null,
    cardId: string | null,
    bin: string | null,
    lastFour: string | null,
    affinityGroupId: string | null,
    origin: string | null,
    merchantId: string | null,
    merchantMcc: string | null,
    merchantName: string | null,
    transactionAmount: string | null,
    transactionCurrency: string | null,
    settlementAmount: string | null,
    settlementCurrency: string | null,
    debtAmount: string | null,
    debtCurrency: string | null,
    reconciliationDate: string | null,
    interchangeFee: string | null,
    interchangeRate: string | null,
    tax: string | null,
    taxId: string | null,
    functionCode: string | null,
    messageReversalIndicator: string | null,
    messageReasonCode: string | null,
    icaAcquirer: string | null,
    installmentsGracePeriod: string | null,
    installmentsQuantity: string | null,
    installmentsCreditType: string | null,
    currentInstallment: string | null,
    documentName: string | null,
    procesDocumentDate: string | null,
    atmFee: string | null,
}