export enum CardReasonEnum {
    CLIENT_INTERNAL_REASON = "CLIENT_INTERNAL_REASON",
    USER_INTERNAL_REASON = "USER_INTERNAL_REASON",
    POMELO_INTERNAL_REASON = "POMELO_INTERNAL_REASON",
    PROVIDER_INTERNAL_REASON = "PROVIDER_INTERNAL_REASON",
    LOST = "LOST",
    STOLEN = "STOLEN",
    BROKEN = "BROKEN",
    UPGRADE = "UPGRADE"
}