export enum OnboardingStepKeyEnum {
    ADDRESS = "ADDRESS",
    ADDRESS_DOCUMENT = "ADDRESS_DOCUMENT",
    CURP = "CURP",
    ACCOUNT_USD = "ACCOUNT_USD",
    PASSWORD = "PASSWORD",
    DOCUMENTS = "DOCUMENTS",
    LIVENESS = "LIVENESS"
}