export enum DirectoryStatusEnum
{
    COMPLETED = "COMPLETED",
    IN_REVIEW = "IN_REVIEW",
    REJECTED = "REJECTED",
    IN_PROCESS = "IN_PROCESS",
    UNREGISTERED = "UNREGISTERED",
    SIGN_UP = "SIGN_UP",
    PRE_REGISTRATION_BY_INVITATION= "PRE_REGISTRATION_BY_INVITATION",
    EXPIRED = "EXPIRED",
}
