export enum BackofficeUploadFileTypeEnum {
    PHONE_CHANGE_EVIDENCE = "PHONE_CHANGE_EVIDENCE",
    DOCUMENT_PHOTO = "UPLOAD_DOCUMENT_PHOTO",
    VIDEO_SELFIE = "VIDEO_SELFIE",
    OTHER_DOCUMENT = "OTHER_DOCUMENT"
}