export enum IdentificationDocumentStatus {
    DEBIT_CARD_PURCHASE = "DEBIT_CARD_PURCHASE",
    MONEY_TRANSFER = "MONEY_TRANSFER",
    ACH_IN = "ACH_IN",
    POCKET_MONEY_TRANSFER = "POCKET_MONEY_TRANSFER",
    CREDIT_CARD_PURCHASE = "CREDIT_CARD_PURCHASE",
    CREDIT_CARD_PAYMENT = "	CREDIT_CARD_PAYMENT",
    ACH_OUT = "ACH_OUT",
    RST_EXECUTION = "RST_EXECUTION",
    CREDIT_CARD_ADJUSTMENT = "CREDIT_CARD_ADJUSTMENT",
    DEBIT_CARD_WITHDRAWAL = "DEBIT_CARD_WITHDRAWAL",
    COLLECTOR = "COLLECTOR"
}